### ISSUE TITLE
Add Vendor Stats Request/Reply message

### ISSUE THREAD

**Issue by yasuhito** [trema/pio#237]

**Comment by yasuhito** [comment]
@shun159 Vendor Stats って使うことありますか?

**Comment by shun159** [comment]
@yasuhito 
nx_flow_modでtable_id >= 1で書いたフローはofpst_flowやofpst_aggregateではみれないはず…。
ですが、すぐに必要になるわけではなさそう。(※nxst_flow, nxst_aggregateの他に、flow_monitorの導入は考えてみてもよいとは思っています。

**Comment by yasuhito** [comment]
@shun159 ありがとうございます。NXの話がよくわかっていないのですが、つまり nx_flow_mod (table_id >=1) したら trema dump_flow に出てこないという理解であってますか?

**Comment by shun159** [comment]
いえ。
確か `trema dump_flow` は `ovs-ofctl dump-flows` だとおもうので、
その時には、NXST_FLOW だとおもいます。問題無いと思います。

**Comment by yasuhito** [comment]
たしかに！ではとりあえず結論としては Vendor Stats は後回しにしておきます。
2015年10月28日(水) 12:55 Eishun Kondoh <notifications@github.com>:
